name: "🐞 Bug Report"
description: Create a report to help us improve
labels: ['bug']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before you submit
      options:
        - label: I have searched existing issues
          required: true
        - label: I spent at least 5 minutes investigating and preparing this report
          required: true
        - label: I confirmed this is not caused by a network issue
          required: true

  - type: markdown
    attributes:
      value: |
        Thank you for using **BabelDOC** and helping us improve it! 🙏

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide your system details (required)
      value: |
        - OS:
        - Python:
        - BabelDOC:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Help us reproduce the issue
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output or Screenshots
      description: Copy and paste any logs or attach screenshots. This will be formatted automatically.
      render: text
    validations:
      required: false

  - type: textarea
    id: pdf
    attributes:
      label: Original PDF File
      description: Upload the input PDF if applicable.
    validations:
      required: false

  - type: textarea
    id: others
    attributes:
      label: Additional Context
      description: Anything else we should know?
    validations:
      required: false
